### ISSUE TITLE
Przygotowanie maszyny wirtualnej

### ISSUE THREAD

**Issue by kgruszowski** [kgruszowski/northwind-python-bazy-danych-4#1]
Trzeba przygotować maszynę wirtualną, proponuję Linux Mint, od razu trzeba przygotować Postgresa z zaimportowaną bazą i serwer pod projekt, proponuję lighthttpd

**Comment by ksiazekm** [comment]
Maszyna zostala przygotowana i udostepniona - link podany na wiki. W razie koniecznosci zmiany beda sledzone w osobnych issues.
